spring.application.name=rest-api

#database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/expensetransactions
spring.datasource.username=postgres
spring.datasource.password=phuan03042004

jwt.secret=yourSecretKeysdasdasdasdadasdassđs

#jpa properties
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true

server.servlet.context-path=/api/v1